<template>
  <!-- THIS FILE IS AUTO-GENERATED BY build/vux-config.js -->
  <group>
    <cell v-for="demo in list" :key="demo.path" is-link :link="demo.path" :title="demo.title[lang]"></cell>
  </group>
</template>

<script>
/* eslint-disable */
export default {
  created () {
    this.lang = this.$locale.get()
  },
  data () {
    return {
      lang: 'en',
      list: [
  {
    "title": {
      "en": "basic usage",
      "zh-CN": "基础用法"
    },
    "path": "/components/x-circle/basic",
    "order": 1
  },
  {
    "title": {
      "en": "gradient",
      "zh-CN": "渐变"
    },
    "path": "/components/x-circle/gradient",
    "order": 2
  }
]
    }
  }
}
</script>
