<template>
  <!-- THIS FILE IS AUTO-GENERATED BY build/vux-config.js -->
  <group>
    <cell v-for="demo in list" :key="demo.path" is-link :link="demo.path" :title="demo.title[lang]"></cell>
  </group>
</template>

<script>
/* eslint-disable */
export default {
  created () {
    this.lang = this.$locale.get()
  },
  data () {
    return {
      lang: 'en',
      list: [
  {
    "title": {
      "en": "基本折线图",
      "zh-CN": "基本折线图"
    },
    "path": "/components/v-chart/line_basic",
    "order": 1
  },
  {
    "title": {
      "en": "折线图:平滑曲线",
      "zh-CN": "折线图:平滑曲线"
    },
    "path": "/components/v-chart/line_smooth_with_dot",
    "order": 1
  },
  {
    "title": {
      "en": "动态数据：实时折线",
      "zh-CN": "动态数据：实时折线"
    },
    "path": "/components/v-chart/line_realtime",
    "order": 1
  },
  {
    "title": {
      "en": "折线图：渐变",
      "zh-CN": "折线图：渐变"
    },
    "path": "/components/v-chart/line_gradient",
    "order": 1
  },
  {
    "title": {
      "en": "折线图:对比",
      "zh-CN": "折线图:对比"
    },
    "path": "/components/v-chart/line_color",
    "order": 1
  },
  {
    "title": {
      "en": "折线图：显示点",
      "zh-CN": "折线图：显示点"
    },
    "path": "/components/v-chart/line_with_dot",
    "order": 1
  },
  {
    "title": {
      "en": "层叠面积图",
      "zh-CN": "层叠面积图"
    },
    "path": "/components/v-chart/area_stack",
    "order": 999
  },
  {
    "title": {
      "en": "层叠柱状图",
      "zh-CN": "层叠柱状图"
    },
    "path": "/components/v-chart/bar_stack",
    "order": 999
  },
  {
    "title": {
      "en": "分组柱状图",
      "zh-CN": "分组柱状图"
    },
    "path": "/components/v-chart/bar_series",
    "order": 999
  },
  {
    "title": {
      "en": "百分比柱状图",
      "zh-CN": "百分比柱状图"
    },
    "path": "/components/v-chart/bar_percent",
    "order": 999
  },
  {
    "title": {
      "en": "基础柱状图",
      "zh-CN": "基础柱状图"
    },
    "path": "/components/v-chart/bar_basic",
    "order": 999
  },
  {
    "title": {
      "en": "带负值面积图",
      "zh-CN": "带负值面积图"
    },
    "path": "/components/v-chart/area_negative",
    "order": 999
  },
  {
    "title": {
      "en": "环图: 资产配置",
      "zh-CN": "环图: 资产配置"
    },
    "path": "/components/v-chart/pie_annular",
    "order": 999
  },
  {
    "title": {
      "en": "渐变填充面积图",
      "zh-CN": "渐变填充面积图"
    },
    "path": "/components/v-chart/area_gradient",
    "order": 999
  },
  {
    "title": {
      "en": "饼图",
      "zh-CN": "饼图"
    },
    "path": "/components/v-chart/pie_basic",
    "order": 999
  },
  {
    "title": {
      "en": "区域图（存在空值）",
      "zh-CN": "区域图（存在空值）"
    },
    "path": "/components/v-chart/area_empty",
    "order": 999
  },
  {
    "title": {
      "en": "散点图",
      "zh-CN": "散点图"
    },
    "path": "/components/v-chart/point",
    "order": 999
  },
  {
    "title": {
      "en": "对比面积图：美国、苏联核储备对比",
      "zh-CN": "对比面积图：美国、苏联核储备对比"
    },
    "path": "/components/v-chart/area_compare",
    "order": 999
  },
  {
    "title": {
      "en": "基础面积图",
      "zh-CN": "基础面积图"
    },
    "path": "/components/v-chart/area_basic",
    "order": 999
  },
  {
    "title": {
      "en": "自定义渲染逻辑",
      "zh-CN": "自定义渲染逻辑"
    },
    "path": "/components/v-chart/prevent_render",
    "order": 999
  }
]
    }
  }
}
</script>
